### ISSUE TITLE
Symfony 5 Support

### ISSUE THREAD

**Issue by ronisaha** [xiidea/EasyAuditBundle#45]
## Todo 

- [x]  Remove Deprecated Functions
- [x]  Get ImpersonatingUser From SwitchUserToken
- [x]  Remove FOSUserbundle Dependency
- [x]  Remove BC Layer
- [x]  Update Documentation
- [x]  Use event from Symfony\Contracts namespace 
- [x] Update PHPUnit
